[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-custom.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom.variants.design]
    y = "straight-turn"
    lower-lambda = "straight-turn"
    zero = "slashed"
    paren = "large-contour"
    number-sign = "upright"
    ampersand = "closed"
    at = "fourfold"
    lig-ltgteq = "flat"
    question = "smooth"

    [buildPlans.iosevka-custom.variants.italic]
    f = "flat-hook"
    long-s = "flat-hook"
    eszet = "sulzbacher"

[buildPlans.iosevka-custom-fixed]
family = "Iosevka Custom Fixed"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-custom-fixed.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom-fixed.variants.design]
    y = "straight-turn"
    lower-lambda = "straight-turn"
    zero = "slashed"
    paren = "large-contour"
    number-sign = "upright"
    ampersand = "closed"
    at = "fourfold"
    lig-ltgteq = "flat"
    question = "smooth"

    [buildPlans.iosevka-custom-fixed.variants.italic]
    f = "flat-hook"
    long-s = "flat-hook"
    eszet = "sulzbacher"

[buildPlans.iosevka-custom-term]
family = "Iosevka Custom Term"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-custom-term.variants]
  inherits = "ss14"

    [buildPlans.iosevka-custom-term.variants.design]
    y = "straight-turn"
    lower-lambda = "straight-turn"
    zero = "slashed"
    paren = "large-contour"
    number-sign = "upright"
    ampersand = "closed"
    at = "fourfold"
    lig-ltgteq = "flat"
    question = "smooth"

    [buildPlans.iosevka-custom-term.variants.italic]
    f = "flat-hook"
    long-s = "flat-hook"
    eszet = "sulzbacher"
